name: Mule CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Application
        run: mvn clean compile

      - name: Package Application
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar